# Kafka Configuration for MSK (used by direct producer)
kafka.bootstrap.servers=${MSK_BROKERS:boot-zosnm4je.c3.kafka-serverless.ap-south-1.amazonaws.com:9098}

# Lambda Configuration
quarkus.package.type=fast-jar
quarkus.lambda.handler=org.pluralsight.LambdaFunction::handleRequest
